name: Release Application

on:
  push:
    branches:
      - "**"

env:
  OPENSHIFT_SERVER: "https://api.rm2.thpm.p1.openshiftapps.com:6443"
  OPENSHIFT_NAMESPACE: "wout-slaets-dev"

jobs:
  deploy:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/tst'
    environment: development
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OC_TOKEN }}
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}

      - name: Apply Openshift YAML
        run: |
          kubectl apply -f infra/openshift.yaml -n $OPENSHIFT_NAMESPACE
