name: Golang Docker Build

on:
  push:
    branches:
      - "**"

env:
  CONTAINER_REPOSITORY: quay.io/wout_slaets # PUT YOUR OWN USERNAME HERE
  CONTAINER_IMAGE: alm-workshop
  GOLANG_VERSION: 1.23

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Quay.io login
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: wout_slaets+wout_s_robot
          password: LXTHE8KS2A957S3L4C362X3KRKZ25FFOXWE6A1DGYA41FCYL8JKS9DCABOKDK94J

      - name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: quay.io/wout_slaets/alm-workshop

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
